var data = [
	{
		"SUBCODE": "01A",
		"EXPLANATION": "LATE ASSIGNMENT OF SUBCHARTER A/C BY SUBCHARTER COMPANY DUE TO TECHNICAL REASONS",
		"RESPONSIBLE": "CHARTER SALES"
	},
	{
		"SUBCODE": "01B",
		"EXPLANATION": "LATE ASSIGNMENT OF SUBCHARTER A/C BY SUBCHARTER COMPANY OTHER THAN TECHNICAL REASON",
		"RESPONSIBLE": "CHARTER SALES"
	},
	{
		"SUBCODE": "01C",
		"EXPLANATION": "DELAY BECAUSE OF AVAILABILITY OF SUBCHARTER A/C IS LATER THAN SCHEDULED TIME OF DEPARTURE",
		"RESPONSIBLE": "CHARTER SALES"
	},
	{
		"SUBCODE": "01D",
		"EXPLANATION": "DELAY DUE TO SUBCHARTER CANCELLATION BY SUBCHARTER COMPANY",
		"RESPONSIBLE": "CHARTER SALES"
	},
	{
		"SUBCODE": "01E",
		"EXPLANATION": "DELAY DUE TO GIVEN SUBCHARTER",
		"RESPONSIBLE": "CHARTER SALES"
	},
	{
		"SUBCODE": "01X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CHARTER SALES"
	},
	{
		"SUBCODE": "02A",
		"EXPLANATION": "STARTING ENGINE WITH EXTERNAL POWER UNIT (ASU / GPU)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "02B",
		"EXPLANATION": "ENGINE START PROCEDURES AT PARKING POSITION FOR TOW CARLESS OPERATION",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "02X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "PUNCT"
	},
	{
		"SUBCODE": "03A",
		"EXPLANATION": "INTERNAL AUDIT",
		"RESPONSIBLE": "QUALITY"
	},
	{
		"SUBCODE": "03B",
		"EXPLANATION": "EXTERNAL AUDIT",
		"RESPONSIBLE": "QUALITY"
	},
	{
		"SUBCODE": "03X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "QUALITY"
	},
	{
		"SUBCODE": "04A",
		"EXPLANATION": "DELAYS UNDER INVESTIGATION",
		"RESPONSIBLE": "PUNCT"
	},
	{
		"SUBCODE": "05A",
		"EXPLANATION": "DELAYS DUE TO ADDITIONAL FLIGHT ENTRY (OTHER THAN SUBCHARTER)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "05B",
		"EXPLANATION": "DELAYS DUE TO PERMI PROBLEM",
		"RESPONSIBLE": "CHARTER SALES"
	},
	{
		"SUBCODE": "05X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "PUNCT"
	},
	{
		"SUBCODE": "06A",
		"EXPLANATION": "SUNEXPRESS' OVERPLANNING TO AN AIRPORT WITH LIMITED CONDITIONS",
		"RESPONSIBLE": "SCHEDULING"
	},
	{
		"SUBCODE": "06X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "SCHEDULING"
	},
	{
		"SUBCODE": "09B",
		"EXPLANATION": "SHORT GROUNDTIME PLANNING BY SCHEDULING",
		"RESPONSIBLE": "SCHEDULING"
	},
	{
		"SUBCODE": "09C",
		"EXPLANATION": "SHORT PLANNED GROUND TIME AFTER 4TH DOMESTIC LEG (ACCORDING TO GOM 45 MIN GROUND TIME SHOULD BE PLANNED AFTER 4TH DOMESTIC LEG FOR CLEANING)",
		"RESPONSIBLE": "SCHEDULING"
	},
	{
		"SUBCODE": "09X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "PUNCT"
	},
	{
		"SUBCODE": "11A",
		"EXPLANATION": "LATE CHECK-IN OF TRANSFER PAX",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "11B",
		"EXPLANATION": "ACCEPTANCE OF STAND-BY PAX",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "11C",
		"EXPLANATION": "LATE CHECK-IN OF PAX WITH SUNEXPRESS' SPECIAL REQUEST",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "11D",
		"EXPLANATION": "CHECK IN COULD NOT BE CLOSED ON TIME DUE TO UNEXPERIENCED OR INADEQUATE NUMBER OF CHECK-IN STAFF",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "11E",
		"EXPLANATION": "LATE PROCEEDING GROUP PAX TO CHECK-IN",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "11F",
		"EXPLANATION": "LATE CHECK-IN  DUE TO UNPREDICTABLE OBSTACLES ON THE WAY TO AIRPORT",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "11N",
		"EXPLANATION": "LATE CHECK-IN DUE TO COLLECTION OF EXCESS BAGGAGE FEES",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "11O",
		"EXPLANATION": "LATE CHECK-IN OF REROUTED PAX (DUE TO CANCELLATION ETC.)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "11P",
		"EXPLANATION": "LATE CHECK-IN DUE TO BOOKING PROBLEM",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "11R",
		"EXPLANATION": "CHECK-IN AFTER DEADLINE FOR DEADHEAD CREW. ",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "11X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "12A",
		"EXPLANATION": "CONGESTION AT CHECK-IN AREA  (E.G. LATE ARRIVED MASS OF PAX , CLOSE TO CLOSURE TIME)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "12B",
		"EXPLANATION": "LACK OF ADDITIONAL PERSONNEL TO CLOSE CHECK-IN ON-TIME",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "12C",
		"EXPLANATION": "CONGESTION AT TRANSFER AREA",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "12D",
		"EXPLANATION": "LATE GROUP CHECK-IN DUE TO CONGESTION AT TERMINAL",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "12X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "13A",
		"EXPLANATION": "CHECK-IN ERRORS RELATED TO APIS,SPECIAL LOADS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "13B",
		"EXPLANATION": "CHECK-IN ERROR DUE TO STAFF FAILURE",
		"RESPONSIBLE": ""
	},
	{
		"SUBCODE": "13K",
		"EXPLANATION": "DOUBLE CHECK-IN",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "13L",
		"EXPLANATION": "DOCUMENTATION ERROR (VISA,TICKET,ETC.)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "13M",
		"EXPLANATION": "EDITING ERROR (CHECK-IN ERRORS DUE TO MISSING SPECIAL INFOS)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "13X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "14A",
		"EXPLANATION": "OVERSALES/OVERBOOK",
		"RESPONSIBLE": "COMMERCIAL/SALES"
	},
	{
		"SUBCODE": "14B",
		"EXPLANATION": "RESERVATION ERRORS",
		"RESPONSIBLE": "COMMERCIAL/SALES"
	},
	{
		"SUBCODE": "14O",
		"EXPLANATION": "OVERBOOKING DUE TO OPERATIONAL REASONS (A/C CHANGE, INOP SEAT, ETC.)",
		"RESPONSIBLE": "COMMERCIAL/SALES"
	},
	{
		"SUBCODE": "14P",
		"EXPLANATION": "ACCEPTANCE OF PAX FROM ANOTHER OVERBOOKED FLIGHT.",
		"RESPONSIBLE": "COMMERCIAL/SALES"
	},
	{
		"SUBCODE": "14R",
		"EXPLANATION": "RESERVATION ERRORS FOR SPECIAL PAX (AVIH,WCHR ETC.)",
		"RESPONSIBLE": "COMMERCIAL/SALES"
	},
	{
		"SUBCODE": "14S",
		"EXPLANATION": "ETICKET RESERVATION ERRORS",
		"RESPONSIBLE": "COMMERCIAL/SALES"
	},
	{
		"SUBCODE": "14T",
		"EXPLANATION": "RESERVATION ERRORS BY TOUR OPERATORS",
		"RESPONSIBLE": "COMMERCIAL/SALES"
	},
	{
		"SUBCODE": "14X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "COMMERCIAL/SALES"
	},
	{
		"SUBCODE": "15A",
		"EXPLANATION": "BOARDING ERROR/INCOMPATIBILITY OF PAX FIGURES",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "15B",
		"EXPLANATION": "LATE BOARDING START BY HANDLING COMPANY DUE TO LONG PROCEDURES (REGARDING AUTOMATIC BOARDING START TIME)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "15C",
		"EXPLANATION": "SLOW BOARDING (POOR/INEFFICIENT COORDINATION OF BOARDING PROCESS)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "15D",
		"EXPLANATION": "MISSING/LATE SHOWN UP CHECKED-IN PAX",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "15E",
		"EXPLANATION": "LATE COBUS REQUEST BY BOARDING STAFF",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "15F",
		"EXPLANATION": "LATE BOARDING DUE TO DOCUMENT CHECK (TICKET,VISA,PASSPORT,API, ETC.)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "15G",
		"EXPLANATION": "LACK OF BOARDING STAFF",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "15I",
		"EXPLANATION": "OVERSIZED HAND BAGGAGE HANDLING. (COLLECTION, LOADING, ISSUING EXCESS TICKET)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "15Q",
		"EXPLANATION": "LATE/INCORRECT INFO ABOUT COLLECTED BAGGAGES AT GATE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "15P",
		"EXPLANATION": "LOADING OF UNIDENTIFIED BAGGAGE UPON CONFIRMATION OF OWNER",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "15R",
		"EXPLANATION": "MISDIRECTING OF PAX TO THE WRONG PARKING POSITION/WRONG GATE ",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "15S",
		"EXPLANATION": "LATE/LONG BOARDING DUE TO STAFF FAILURE (SICKNESS OF BOARDING STAFF,etc)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "15U",
		"EXPLANATION": "RESEATING AT GATE DUE TO A/C CHANGE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "15X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "16A",
		"EXPLANATION": "VIP BOARDING",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "16B",
		"EXPLANATION": "HANDLING OF UNRULY PAX",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "16D",
		"EXPLANATION": "MISSING PAX' PERSONAL ITEMS (THIS CODE WILL BE USED ALSO FOR CASES; MOBILE PHONE FORGOTTEN OPEN INSIDE HOLD BAGGAGE )",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "16E",
		"EXPLANATION": "DEPO/INAD HANDLING",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "16F",
		"EXPLANATION": "REFRESHMENT SERVICE DUE TO IRREGULARITY",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "16G",
		"EXPLANATION": "DEPLANE OF PAX BY OWN WILL",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "16H",
		"EXPLANATION": "SICK/DEAD PAX OR BIRTH ON BOARD",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "16I",
		"EXPLANATION": "EXTENDED BOARDING/DEBOARDING DUE TO PAX PROFILE (SLOW MOVING PAX I.E.)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "16N",
		"EXPLANATION": "PRESS ACTIVITIES ON BOARD",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "16S",
		"EXPLANATION": "ACCEPTANCE OF PAX FROM ANOTHER AIRLINE (NOT CONNECTING)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "16X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "17A",
		"EXPLANATION": "LATE CATERING ORDER",
		"RESPONSIBLE": "CATERING"
	},
	{
		"SUBCODE": "17B",
		"EXPLANATION": "WRONG CATERING ORDER",
		"RESPONSIBLE": "CATERING"
	},
	{
		"SUBCODE": "17O",
		"EXPLANATION": "ADDITIONAL CATERING REQUEST ( DUE TO CONSUMED/SPOILED RETURN MEAL ETC.)",
		"RESPONSIBLE": "CREWCA"
	},
	{
		"SUBCODE": "17P",
		"EXPLANATION": "LATE CATERING ORDER FOR RETURN FLIGHT",
		"RESPONSIBLE": "CATERING"
	},
	{
		"SUBCODE": "17X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CATERING"
	},
	{
		"SUBCODE": "18A",
		"EXPLANATION": "LATE DELIVERY OF HOLD BAGGAGE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "18C",
		"EXPLANATION": "BAGGAGE RECONCILIATION AND ASSORTMENT PROBLEMS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "18N",
		"EXPLANATION": "RUSH BAGGAGES OF OWN COMPANY",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "18O",
		"EXPLANATION": "RUSH BAGGAGES OF OTHER AIRLINES",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "18Q",
		"EXPLANATION": "INSUFFICIENT BAGGAGE RECONCILIATION EQUIPMENT",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "18R",
		"EXPLANATION": "MISDIRECTING OF BAGGAGES TO WRONG FLIGHT",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "18S",
		"EXPLANATION": "ERRORS OF THE BAGGAGE RECONCILIATION COORDINATION OFFICE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "18X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "19A",
		"EXPLANATION": "BOARDING OF PAX WITH REDUCED MOBILITY",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "19B",
		"EXPLANATION": "DEBOARDING OF PAX WITH REDUCED MOBILITY",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "19C",
		"EXPLANATION": "DELAY CAUSED BY SLOW/ERRONEOUS PRM SERVICE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "19D",
		"EXPLANATION": "DELAY CAUSED BY AD-HOC (NOT PRE-BOOKED) PAX WITH REDUCED MOBILITY",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "19X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "21A",
		"EXPLANATION": "LATE CARGO FIGURE",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "21B",
		"EXPLANATION": "INCORRECT CARGO FIGURE",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "21C",
		"EXPLANATION": "LATE CARGO DOCUMENTS (NOTOC,CUSTOM DOC,CGO MANIFEST)",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "21D",
		"EXPLANATION": "INCORRECT CARGO DOCUMENTS",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "21X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "22A",
		"EXPLANATION": "CHANGE OF LOADING DUE TO MISSING CARGO",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "22B",
		"EXPLANATION": "LACK OF CARGO STAFF",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "22C",
		"EXPLANATION": "INADEQUACY  / LACK OF CARGO EQUIPMENT",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "22D",
		"EXPLANATION": "LATE,INCORRECT CARGO DELIVERY, CARGO DELIVERY TO WRONG PARKING POSITION",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "22N",
		"EXPLANATION": "LATE PROVISION OF LOADING MATERIALS (ROPE,LOAD SPREADERS ETC.)",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "22O",
		"EXPLANATION": "CARGO STAFF ERROR",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "22X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "23A",
		"EXPLANATION": "LATE ACCEPTANCE OF CARGO DUE TO COMMERCIAL REASONS",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "23B",
		"EXPLANATION": "STAND-BY CARGO ACCEPTANCE",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "23C",
		"EXPLANATION": "INADEQUACY  / LACK OF CARGO STAFF",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "23X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "24A",
		"EXPLANATION": "CHANGE AT WEIGHT OF CARGO",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "24B",
		"EXPLANATION": "INADEQUATE PACKING OF DANGEROUS GOODS",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "24X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "25A",
		"EXPLANATION": "OVERSALES",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "25B",
		"EXPLANATION": "CARGO RESERVATION/BOOKING ERRORS",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "25C",
		"EXPLANATION": "STAND-BY CARGO ACCEPTANCE",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "25X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "26D",
		"EXPLANATION": "INADEQUATE NUMBER OF STAFF",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "26E",
		"EXPLANATION": "WAREHOUSE CONGESTION",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "26X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "27A",
		"EXPLANATION": "LATE MAIL FIGURES",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "27B",
		"EXPLANATION": "WRONG MAIL FIGURES",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "27C",
		"EXPLANATION": "LATE DOCUMENTATION",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "27D",
		"EXPLANATION": "INACCURATE DOCUMENTATION",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "27X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "28A",
		"EXPLANATION": "RE-LOADING DUE TO MISSING MAIL",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "28B",
		"EXPLANATION": "INADEQUATE NUMBER OF STAFF",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "28C",
		"EXPLANATION": "INADEQUACY/LACKING OF EQUIPMENT (TRACTOR, CARGO CARRIER ETC.)",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "28D",
		"EXPLANATION": "MOVING to WRONG PARKING POSITION OR MOVING TO PARKING POSITION WITH MISSING CGO.",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "28N",
		"EXPLANATION": "DUE TO THE PERSONNEL",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "28X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "29A",
		"EXPLANATION": "LATE ACCEPTANCE OF MAIL - COMMERCIAL REASONS",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "29B",
		"EXPLANATION": "STAND-BY MAIL ACCEPTANCE",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "29C",
		"EXPLANATION": "INADEQUATE NUMBER OF STAFF",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "29X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "31A",
		"EXPLANATION": "LATE DELIVERY OF DOCUMENTS TO COCKPIT (OTHER THAN LOAD AND TRIM SHEET I.E. OFP , CUSTOM DOCUMENTS, NOTOC, PAX MANIFEST)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "31B",
		"EXPLANATION": "INCORRECT DOCUMENTS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "31C",
		"EXPLANATION": "LATE LOAD AND TRIM SHEET (REGARDING STD-5MINUTES FOR DOMESTIC FLIGHTS, STD-10 MINUTES FOR INTERNATIONAL FLIGHTS)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "31D",
		"EXPLANATION": "WRONG LOAD AND TRIM SHEET",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "31E",
		"EXPLANATION": "REPOSITIONING OF PAX/CARGO DUE TO TRIM-OUT",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "31F",
		"EXPLANATION": "INCORRECT DATA ON DCS SYSTEM (SEAT CHART,HOLD VERSION)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "31G",
		"EXPLANATION": "INADEQUATE/LACK OF OPERATION AGENT",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "31H",
		"EXPLANATION": "ERRORS ON LOADING INSTRUCTION",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "31I",
		"EXPLANATION": "LATE DELIVERY OF FUEL FIGURES TO LOAD OFFICE BY RAMP AGENT",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "31N",
		"EXPLANATION": "LAST MINUTE DOCUMENT CHANGE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "31O",
		"EXPLANATION": "OPERATION AGENT FAILURE (LATE OPERATION,SICKNESS OF AGENT,ABANDONMENT, etc)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "31P",
		"EXPLANATION": "OTHER ERRORS RELATED TO OPERATION AGENT AT A/C",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "31X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "32A",
		"EXPLANATION": "SPECIAL LOADS (OVERSIZED LOAD, AVIH,HEA,HUM ETC.)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "32B",
		"EXPLANATION": "LATE START/COMPLETION OF LOADING",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "32C",
		"EXPLANATION": "INADEQUATE NUMBER OF STAFF",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "32D",
		"EXPLANATION": "IMPROPER LOADING (NOT IN COMPLIANCE WITH LOAD PLAN OR THE LOADING PRINCIPLES)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "32G",
		"EXPLANATION": "LATE LOADING MATERIALS (ROPE,HOOK,PLANK ETC.)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "32H",
		"EXPLANATION": "LONG DURATION OF LOADING/UNLOADING DUE TO HIGH NUMBER OF BAGGAGE/LOAD.",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "32M",
		"EXPLANATION": "LATE START/COMLETION OF UNLOADING",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "32N",
		"EXPLANATION": "RAMP STAFF FAILURE ( LATE OPERATION, SICKNESS OR ABANDONMENT  OF BY RAMP STAFF )",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "32R",
		"EXPLANATION": "LONG/WRONG SEARCHING FOR PAX BAGGAGE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "32S",
		"EXPLANATION": "LAST MINUTE LOADING ALTERATIONS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "32W",
		"EXPLANATION": "IMPROPER LOADING AT INCOMING FLIGHT FROM DEPARTURE STATION (UNTIED NETS; OPEN AVIH CAGE ETC.)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "32X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "33A",
		"EXPLANATION": "LATE EQUIPMENT (TRACTOR,CONVEYOR ETC.)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "33B",
		"EXPLANATION": "LACK OF EQUIPMENT",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "33C",
		"EXPLANATION": "LACK OF EQUIPMENT OPERATORS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "33D",
		"EXPLANATION": "UNSERVICEABLE EQUIPMENT",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "33E",
		"EXPLANATION": "WRONG EQUIPMENT ARRANGEMENTS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "33X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "34A",
		"EXPLANATION": "ABSENCE/LATE ARRIVAL OF BOARDING BRIDGE OPERATORS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "34B",
		"EXPLANATION": "LATE/BROKEN/ABSENT STEPS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "34C",
		"EXPLANATION": "LACK OR LATE ARRIVAL OF  BUS/MIDIBUS (PAX,VIP,CREW)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "34D",
		"EXPLANATION": "LACK OR LATE ARRIVAL OF POTABLE WATER SERVICE VEHICLE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "34E",
		"EXPLANATION": "LACK OR LATE ARRIVAL OF LAVATORY SERVICE VEHICLE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "34F",
		"EXPLANATION": "INADEQUATE NUMBER OF STAFF",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "34G",
		"EXPLANATION": "EQUIPMENT THAT IS NOT SUITABLE FOR PAX DURING BOARDING/DEBOARDING(ICE/SNOW ON STAIRS ETC.)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "34O",
		"EXPLANATION": "LACK OR LATE ARRIVAL OF AMBULIFT",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "34X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "35A",
		"EXPLANATION": "LATE COMPLETION OF CLEANING (SLOW CLEANING STAFF; DIRTY A/C ETC.)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "35B",
		"EXPLANATION": "INSUFFICIENT CLEANING EQUIPMENT",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "35C",
		"EXPLANATION": "FAILURE OF EQUIPMENT (GARBAGE TRUCK,VACUUM CLEANER ETC.)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "35D",
		"EXPLANATION": "LATE ARRIVAL OR INADEQUATE NUMBER OF CLEANING STAFF",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "35E",
		"EXPLANATION": "RECLEANING DUE TO  IMPROPER CLEANING",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "35F",
		"EXPLANATION": "NECESSARY ADDITIONAL OR SPECIAL CLEANING REQUESTS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "35G",
		"EXPLANATION": "CLEANING OF THE COCKPIT WINDOWS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "35H",
		"EXPLANATION": "LATE OR INCORRECT DELIVERY OF THE CABIN SERVICE ITEMS BY CLEANING PERSONNEL",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "35W",
		"EXPLANATION": "ADDITIONAL CLEANING REQUEST DUE TO  BAD WEATHER CONDITIONS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "35X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "36A",
		"EXPLANATION": "LACK OF FUEL VEHICLE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "36B",
		"EXPLANATION": "LATE ARRIVAL OF FUEL VEHICLE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "36C",
		"EXPLANATION": "FUEL VEHICLE FAILURE DURING OPERATION",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "36D",
		"EXPLANATION": "LATE DE-FUELING DUE TO UNAVAILABILITY OF APPROPRIATE VEHICLE/ EQUIPMENT.",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "36E",
		"EXPLANATION": "INADEQUATE NUMBER OF STAFF",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "36F",
		"EXPLANATION": "FUELING ERROR DUE TO STAFF MISTAKE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "36G",
		"EXPLANATION": "IMPLEMENTATION OF SPECIAL PROCEDURE DUE TO TECHNICAL REASONS",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "36H",
		"EXPLANATION": "FAILURE OF FUEL HYDRANT SYSTEM VEHICLE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "36I",
		"EXPLANATION": "NEW FUEL SERVICE DUE TO POOR FUEL QUALITY/CONTAMINATED FUEL",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "36J",
		"EXPLANATION": "SPILLAGE OF FUEL",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "36K",
		"EXPLANATION": "UNABLE TO FUELLING DUE TO THE IMPROPER PARKING OF A/C OR GSE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "36X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "37A",
		"EXPLANATION": "SLOW CATERING UPLOAD (DUE TO LACK OF STAFF; UNEXPERIENCED STAFF ETC)",
		"RESPONSIBLE": "CATERING"
	},
	{
		"SUBCODE": "37B",
		"EXPLANATION": "COMMUNICATION PROBLEMS WITH CATERING COMPANY/INTERMEDIARY FIRM (RIM ETC.)",
		"RESPONSIBLE": "CATERING"
	},
	{
		"SUBCODE": "37C",
		"EXPLANATION": "CATERING EQUIPMENT FAILURE",
		"RESPONSIBLE": "CATERING"
	},
	{
		"SUBCODE": "37D",
		"EXPLANATION": "LATE ARRIVAL OF CATERING",
		"RESPONSIBLE": "CATERING"
	},
	{
		"SUBCODE": "37E",
		"EXPLANATION": "INCORRECT OR INADEQUATE CATERING LOADING (INCLUDING CASSETTES,NEWSPAPERS, ETC.)",
		"RESPONSIBLE": "CATERING"
	},
	{
		"SUBCODE": "37G",
		"EXPLANATION": "FAILURE IN LOADING THE RETURN FLIGHT CATERING AT THE PREVIOUS STATION",
		"RESPONSIBLE": "CATERING"
	},
	{
		"SUBCODE": "37R",
		"EXPLANATION": "CHANGE OF CATERING LOADING DUE TO A/C CHANGE",
		"RESPONSIBLE": "CATERING"
	},
	{
		"SUBCODE": "37S",
		"EXPLANATION": " THE GROUND TIME OF THE A/C BEING SHORTER THAN THE CATERING LOADING TIME AS PER THE CATERING CONTRACT",
		"RESPONSIBLE": "CATERING"
	},
	{
		"SUBCODE": "37X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CATERING"
	},
	{
		"SUBCODE": "38A",
		"EXPLANATION": "INADEQUATE NUMBER OF ULDS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "38B",
		"EXPLANATION": "DAMAGED OR UNSERVICEABLE ULD",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "38C",
		"EXPLANATION": "LATE ULD SUPPLY TO HANDLING UNIT",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "38X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "39A",
		"EXPLANATION": "LACK/BREAKDOWN/LATE ARRIVAL OF GPU",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "39B",
		"EXPLANATION": "LACK/BREAKDOWN/LATE ARRIVAL OF DE-ICING VEHICLE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "39C",
		"EXPLANATION": "LACK/BREAKDOWN/LATE ARRIVAL OF TOW BAR",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "39D",
		"EXPLANATION": "LACK/BREAKDOWN/LATE ARRIVAL OF AIR STARTER",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "39E",
		"EXPLANATION": "LACK/BREAKDOWN/LATE ARRIVAL OF AIR CONDITIONER",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "39F",
		"EXPLANATION": "LACK/BREAKDOWN/LATE ARRIVAL OF PUSH BACK VEHICLE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "39G",
		"EXPLANATION": "LACK OF GROUND TECHNICAL EQUIPMENT STAFF/OPERATOR",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "39H",
		"EXPLANATION": "LACK/BREAKDOWN/LATE ARRIVAL OF OTHER TECHNICAL EQUIPMENT",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "39X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "41A",
		"EXPLANATION": "TECHNICAL DEFECTS",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "41E",
		"EXPLANATION": "AWAITING DEPARTURE EQUIPMENT (TECHNICAL EIC Etc.)",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "41N",
		"EXPLANATION": "AWAITING CABIN-COCKPIT MAINTENANCE LOGBOOK",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "41O",
		"EXPLANATION": "DELAY DUE TO MEL INVESTIGATION",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "41P",
		"EXPLANATION": "CHANGE OF THE STATUS OF MEL (FROM GO-TO TO NO-GO)",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "41Q",
		"EXPLANATION": "LATE/INADEQUATE NUMBER OF STAFF",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "41R",
		"EXPLANATION": "DEFECTIVE STATUS/REFILLING OF EMERGENCY EQUIPMENT",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "41S",
		"EXPLANATION": "MISSING TECHNICAL DOCUMENTATION",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "41T",
		"EXPLANATION": "LATE REPORTING OF TECHNICAL DEFECT BY THE MECHANIC",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "41X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "42A",
		"EXPLANATION": "LATE DOCUMENTATION",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "42B",
		"EXPLANATION": "LATE RELEASE BY MAINTENANCE",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "42P",
		"EXPLANATION": "LATE DOCUMENTATION (THIRD PARTY MAINTENANCE)",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "42R",
		"EXPLANATION": "LATE RELEASE BY MAINTENANCE(THIRD PARTY)",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "42X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "43A",
		"EXPLANATION": "LATE/INADEQUATE NUMBER OF TECHNICAL STAFF",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "43B",
		"EXPLANATION": "LATE DOCUMENTATION",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "43N",
		"EXPLANATION": "LATE CHECK ON GROUND",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "43P",
		"EXPLANATION": "TIRE-BREAK UNIT CHANGE",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "43X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "44A",
		"EXPLANATION": "LACK OF SPARE PARTS",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "44B",
		"EXPLANATION": "LACK/BREAKDOWN OF TECHNICAL MAINTENANCE EQUIPMENT",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "44C",
		"EXPLANATION": "LATE DELIVERY OF SPARE PART FROM WAREHOUSE",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "44N",
		"EXPLANATION": "LACK OF FURNISHINGS (SEAT COVER,CURTAIN, ETC.)",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "44Q",
		"EXPLANATION": "INCOMPATIBLE SPARE PARTS DELIVERED BY WAREHOUSE",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "44X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "45A",
		"EXPLANATION": "LATE DELIVERY OF AOG SPARE PARTS",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "45B",
		"EXPLANATION": "LATE DELIVERY OF AOG SPARE PART DOCUMENTS",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "45D",
		"EXPLANATION": "REPLANNING THE LOADING OF A/C BECAUSE OF LOADED SPARES",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "45F",
		"EXPLANATION": "LOADING OF SPARE PART FOR THIRD PARTY AOG",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "45N",
		"EXPLANATION": "DISPATCHING OF TECHNICAL STAFF TO THE STATION, WHERE THE AOG A/C IS LOCATED",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "45X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "46C",
		"EXPLANATION": "CHANGE OF A/C DUE TO PLANNED MAINTENANCE ACTIVITY ",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "46E",
		"EXPLANATION": "CHANGE OF A/C DUE TO LATE DELIVERY BY MAINTENANCE",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "46N",
		"EXPLANATION": "CHANGE OF A/C DUE TO TECHNICAL DEFECT",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "46X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "47A",
		"EXPLANATION": "STAND-BY A/C (LACK OF PLANNED STAND BY A/C FOR TECHNICAL REASONS)",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "47X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "48A",
		"EXPLANATION": "CABIN DIVIDER/SEAT ADJUSTMENT",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "48B",
		"EXPLANATION": "RESERVED",
		"RESPONSIBLE": "NA"
	},
	{
		"SUBCODE": "48C",
		"EXPLANATION": "MEDICAL EQUIPMENT",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "48D",
		"EXPLANATION": "CREW REST SEATING",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "48X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "51A",
		"EXPLANATION": "LIGHTING STRIKE",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "51B",
		"EXPLANATION": "BIRD STRIKE",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "51C",
		"EXPLANATION": "OTHER DAMAGES DURING FLIGHT OPERATIONS (CARGO AND BAGGAGE DAMAGES INCL.)",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "51D",
		"EXPLANATION": "DAMAGE DUE TO BAD WEATHER CONDITIONS (HAIL,TURBULENCE ETC.)",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "51E",
		"EXPLANATION": "OVERWEIGHT / HEAVY LANDING / HARD LANDING",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "51F",
		"EXPLANATION": "COLLISION DURING TAXIING",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "51G",
		"EXPLANATION": "A/C VEER OFF THE RUNWAY OR TAXIWAY",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "51H",
		"EXPLANATION": "FOD DAMAGE (WHEEL/TIRE, INLET COWL, FUSELAGE, FLAPS,SPOILER, ETC)",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "51J",
		"EXPLANATION": "DAMAGING OF A/C BY THE PAX (INCLUDING THE BLOCKAGE OF TOILETS AND LAVATORY)",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "51K",
		"EXPLANATION": "COOLING OF OVERHEATED A/C'S BRAKES",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "51N",
		"EXPLANATION": "A/C CHANGE DUE TO DAMAGE DURING FLIGHT OPERATION",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "51X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "52A",
		"EXPLANATION": "COLLISION DURING TOWING (OTHER THAN TAXIING)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "52B",
		"EXPLANATION": "DAMAGE TO A/C DUE TO BAD WEATHER CONDITIONS (ON APRON)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "52C",
		"EXPLANATION": "DAMAGE TO A/C BY LOADING EQUIPMENT",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "52D",
		"EXPLANATION": "DAMAGE TO A/C BY BRIDGE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "52E",
		"EXPLANATION": "DAMAGE TO A/C BY STAIRS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "52F",
		"EXPLANATION": "DAMAGE TO A/C BY FUELING EQUIPMENT",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "52G",
		"EXPLANATION": "DAMAGE TO A/C BY GROUND TECHNICAL SUPPORT EQUIPMENT",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "52H",
		"EXPLANATION": "DAMAGE TO A/C BY CATERING EQUIPMENT",
		"RESPONSIBLE": "CATERING"
	},
	{
		"SUBCODE": "52I",
		"EXPLANATION": "DAMAGE TO A/C BY CLEANING EQUIPMENT",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "52J",
		"EXPLANATION": "DAMAGE TO A/C BY PUSH-BACK EQUIPMENT",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "52K",
		"EXPLANATION": "DEPLOYMENT OF SLIDE ACCIDENTALLY BY TECHNICAL PERSONNEL",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "52L",
		"EXPLANATION": "DEPLOYMENT OF SLIDE ACCIDENTALLY BY OPERATIONAL PERSONNEL",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "52M",
		"EXPLANATION": "DEPLOYMENT OF SLIDE ACCIDENTALLY BY FLIGHT PERSONNEL",
		"RESPONSIBLE": "CREWCA"
	},
	{
		"SUBCODE": "52N",
		"EXPLANATION": "DAMAGE TO A/C BY TECHNICAL PERSONNEL/ TECHNICAL EQUIPMENT",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "52O",
		"EXPLANATION": "DAMAGE TO A/C BY OPERATIONAL PERSONNEL",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "52P",
		"EXPLANATION": "A/C CHANGE DUE TO DAMAGE TO A/C DURING GROUND OPERATION",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "52S",
		"EXPLANATION": "DAMAGE TO A/C BY OTHER SERVICING EQUIPMENT (LAVATORY VEHICLE,DEICING,BUS)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "52T",
		"EXPLANATION": "COLLUSION OF 2 A/Cs AT APRON",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "52X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "55A",
		"EXPLANATION": "LOCAL DCS ERRORS,MALFUNCTION (EXCEPT IFLY)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "55B",
		"EXPLANATION": "DCS HOST FAILURES",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "55C",
		"EXPLANATION": "HOST NETWORK FAILURES",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "55D",
		"EXPLANATION": "LOCAL NETWORK FAILURES",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "55E",
		"EXPLANATION": "KIOSK FAILURES",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "55N",
		"EXPLANATION": "EQUIPMENT FAILURES  (CHECK-IN,BOARDING,APIS ETC.)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "55O",
		"EXPLANATION": "FAILURES OF PROGRAMS USED BY OPERATION OFFICES (FOR LOADSHEET PREPARATION ETC.)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "55P",
		"EXPLANATION": "BAGGAGE RECONCILIATION SYSTEM FAILURE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "55S",
		"EXPLANATION": "NETLINE-OPS SYSTEM FAILURE",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "55T",
		"EXPLANATION": "TICKETING AND RESERVATION SYSTEM FAILURE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "55U",
		"EXPLANATION": "COMMUNICATION SYSTEM FAILURE (PROBLEMS AT RADIO COMMUNICATION NETWORK, TELEPHONE NETWORK ETC.)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "55X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "56A",
		"EXPLANATION": "LOCAL EQUIPMENT FAILURES",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "56B",
		"EXPLANATION": "HOST FAILURE",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "56C",
		"EXPLANATION": "HOST NETWORK FAILURE",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "56D",
		"EXPLANATION": "LOCAL NETWORK FAILURE",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "56E",
		"EXPLANATION": "AUTOMATED CUSTOM CONTROL SYSTEM FAILURE",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "56X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "57A",
		"EXPLANATION": "LOCAL EQUIPMENT FAILURE",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "57B",
		"EXPLANATION": "HOST FAILURE",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "57C",
		"EXPLANATION": "HOST NETWORK FAILURE",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "57D",
		"EXPLANATION": "LOCAL NETWORK FAILURE",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "57E",
		"EXPLANATION": "COMMUNICATION FAILURE BETWEEN A/C AND ATC SYSTEM",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "57F",
		"EXPLANATION": "FMS FAILURE",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "57G",
		"EXPLANATION": "LATE FLIGHT PLAN DUE TO SYSTEM FAILURE (LIDO, AFTN, SITA E-MAIL ETC.)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "57X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "58A",
		"EXPLANATION": "HANDLING COMPANY RELATED SYSTEM FAILURES",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "58B",
		"EXPLANATION": "TECHNICAL SYSTEM FAILURE OR BREAKDOWN",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "58C",
		"EXPLANATION": "FAILURES OF OTHER SUPPLIERS' SYSTEMS (CATERING,FUEL,ETC.)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "58X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "61B",
		"EXPLANATION": "LATE COMPLETION/SENDING OF FLIGHT DOCUMENTS BY DISPATCH",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "61C",
		"EXPLANATION": "INCORRECT FLIGHT DOCUMENTS BY DISPATCH  (E.G. INCORRECT  FUEL PLANNING)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "61D",
		"EXPLANATION": "LATE FILLING OR LATE UPDATING OF ATC FLIGHT PLAN",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "61E",
		"EXPLANATION": "INCORRECT FILLING OF ATC FLIGHT PLAN",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "61F",
		"EXPLANATION": "CHANGE TO FLIGHT PLAN AFTER BRIEFING DUE TO OPERATIONAL REASONS",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "61G",
		"EXPLANATION": "INADEQUATE NUMBER OF/LACK OF DISPATCH STAFF",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "61H",
		"EXPLANATION": "FAILURE IN COMPLETION OF/MISSING NAVKIT DOCS. (JEPPESEN,TAKE-OFF,CSPD ETC.)",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "61I",
		"EXPLANATION": "MISSING A/C DOCUMENTS (MEL,QRH,FCOM E.G.)",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "61K",
		"EXPLANATION": "CHANGE TO FLIGHT PLAN DUE TO LOAD,WEATHER,ATC, CAPTAIN REQUEST, A/C CHANGE, REDUCE DELAY ETC.(OUT OF OCC'S CONTROL)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "61X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "62B",
		"EXPLANATION": "AWAITING OF FINAL WEIGHT (FUEL CRITICAL FLIGHTS)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "62D",
		"EXPLANATION": "FUEL CHANGE DUE TO OPS REQ (ALTRN,NOTAM,WEATHER,SLOT,RUNWAY,ROUTE, ETC. CHANGES)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "62E",
		"EXPLANATION": "LOAD CHANGE DUE TO OPS REQ (ALTRN,NOTAM,WEATHER,SLOT,RUNWAY,ROUTE, ETC. CHANGES)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "62N",
		"EXPLANATION": "FLIGHT OPERATION INSTRUCTIONS",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "62T",
		"EXPLANATION": "TANKERING",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "62X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "63A",
		"EXPLANATION": "DELAY DUE TO LATE ARRIVAL OF ENTIRE CREW",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "63B",
		"EXPLANATION": "DELAY DUE TO LATE ARRIVAL OF COCKPIT CREW",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "63C",
		"EXPLANATION": "LATE  ARRIVAL OF ENTIRE CREW DUE TO LACK OF/LATE APRON TRANSPORTATION VEHICLE",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "63D",
		"EXPLANATION": "LATE ARRIVAL OF COCKPIT CREW DUE TO CREW TRANSPORTATION VEHICLE (TO AIRPORT)",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "63F",
		"EXPLANATION": "LATE ARRIVAL OF CREW TO THE AIRPORT DUE TO AIRPORT ACCESS CONGESTION/CLOSURE",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "63G",
		"EXPLANATION": "LATE DEPARTURE DUE TO COCKPIT TRAINING",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "63H",
		"EXPLANATION": "LONG PRE-FLIGHT DEPARTURE PROCEDURES-ENTIRE CREW -LATE BOARDING START(WHEN BOARDING OK GIVEN LATER THAN AUTOMATIC BOARDING START TIME) ",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "63J",
		"EXPLANATION": "LONG PRE-FLIGHT DEPARTURE PROCEDURES-COCKPIT CREW -LATE  BOARDING START (WHEN BOARDING OK GIVEN LATER THAN AUTOMATIC BOARDING START TIME) ",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "63K",
		"EXPLANATION": "LATE FUEL FIGURES GIVEN TO RAMP AGENT",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "63L",
		"EXPLANATION": "LATE CREW BOARDING DUE TO A/C CHANGE",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "63X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "64A",
		"EXPLANATION": "SICKNESS",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "64B",
		"EXPLANATION": "AWATING STAND-BY CREW",
		"RESPONSIBLE": "CRWP"
	},
	{
		"SUBCODE": "64C",
		"EXPLANATION": "FLIGHT TIME LIMITATIONS",
		"RESPONSIBLE": "CRWP"
	},
	{
		"SUBCODE": "64D",
		"EXPLANATION": "DUE TO MISSING/ ERRONEOUS TRAVEL DOCUMENTS",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "64E",
		"EXPLANATION": "CREW PLANNING OR CREW CONTROL ERROR",
		"RESPONSIBLE": "CRWP"
	},
	{
		"SUBCODE": "64G",
		"EXPLANATION": "INJURY OR DEATH",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "64H",
		"EXPLANATION": "INSUFFICIENT OPERATIONAL RATING (CAT 1/2/3 ETC.) DUE TO  CREW QUALIFICATION.",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "64R",
		"EXPLANATION": "CREW REST TIME LIMITATIONS",
		"RESPONSIBLE": "CRWP"
	},
	{
		"SUBCODE": "64X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "65A",
		"EXPLANATION": "LATE BOARDING START BY CREW (WHEN BOARDING OK GIVEN LATER THAN AUTOMATIC BOARDING START TIME) DUE TO PERSONAL REASONS",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "65B",
		"EXPLANATION": "MAINTENANCE CHECK OUT OF MINIMUM EQUIPMENT LIST",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "65D",
		"EXPLANATION": "UNIDENTIFIED REPORTED TECHNICAL PROBLEM",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "65E",
		"EXPLANATION": "LATE REPORTED TECHNICAL PROBLEM (BY CREW)",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "65N",
		"EXPLANATION": "ADDITIONAL FUEL/ DEFUELING REQUEST BY COCKPIT (ALTHOUGH WITHIN OPERATIONAL LIMIT)",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "65P",
		"EXPLANATION": "DECISION BY CREW TO DENY SICK PAX DESPITE STATUS OF PAX IS ACCEPTABLE ACCORDING TO  COMPANY PROCEDURES. ",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "65X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "66A",
		"EXPLANATION": "DELAY DUE TO LATE CABIN CREW ARRIVAL",
		"RESPONSIBLE": "CREWCA"
	},
	{
		"SUBCODE": "66B",
		"EXPLANATION": "LATE BOARDING OF CABIN CREW DUE TO CREW TRANSPORTATION VEHICLE  (TO AIRPORT) ",
		"RESPONSIBLE": "CREWCA"
	},
	{
		"SUBCODE": "66D",
		"EXPLANATION": "LATE ARRIVAL OF CABIN CREW TO AIRPORT DUE TO AIRPORT ACCESS CONGESTION/CLOSURE",
		"RESPONSIBLE": "CREWCA"
	},
	{
		"SUBCODE": "66H",
		"EXPLANATION": "LATE PRE-FLIGHT DEPARTURE PROCEDURES-CABIN CREW-LATE  BOARDING START (WHEN BOARDING OK IS GIVEN LATER THAN AUTOMATIC BOARDING START TIME) ",
		"RESPONSIBLE": "CREWCA"
	},
	{
		"SUBCODE": "66X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CREWCA"
	},
	{
		"SUBCODE": "67A",
		"EXPLANATION": "SICKNESS",
		"RESPONSIBLE": "CREWCA"
	},
	{
		"SUBCODE": "67B",
		"EXPLANATION": "AWAITING STAND-BY CREW",
		"RESPONSIBLE": "CRWP"
	},
	{
		"SUBCODE": "67C",
		"EXPLANATION": "FLIGHT TIME LIMITATIONS",
		"RESPONSIBLE": "CRWP"
	},
	{
		"SUBCODE": "67D",
		"EXPLANATION": "TRAVEL DOCUMENTS",
		"RESPONSIBLE": "CREWCA"
	},
	{
		"SUBCODE": "67E",
		"EXPLANATION": "CREW PLANNING OR CREW CONTROL ERROR",
		"RESPONSIBLE": "CRWP"
	},
	{
		"SUBCODE": "67G",
		"EXPLANATION": "INJURY OR DEATH",
		"RESPONSIBLE": "CREWCA"
	},
	{
		"SUBCODE": "67R",
		"EXPLANATION": "CREW REST TIME LIMITATIONS",
		"RESPONSIBLE": "CRWP"
	},
	{
		"SUBCODE": "67X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CREWCA"
	},
	{
		"SUBCODE": "68A",
		"EXPLANATION": "HEADCOUNT ERROR",
		"RESPONSIBLE": "CREWCA"
	},
	{
		"SUBCODE": "68C",
		"EXPLANATION": "LATE / WRONG LAVATORY SERVICE REQUEST",
		"RESPONSIBLE": "CREWCA"
	},
	{
		"SUBCODE": "68D",
		"EXPLANATION": "LATE / WRONG CLEANING SERVICE REQUEST",
		"RESPONSIBLE": "CREWCA"
	},
	{
		"SUBCODE": "68F",
		"EXPLANATION": "LATE BOARDING OK GIVEN BY CABIN CREW DUE TO PERSONAL REASONS",
		"RESPONSIBLE": "CREWCA"
	},
	{
		"SUBCODE": "68O",
		"EXPLANATION": "LATE REQUEST OF NON-STANDART SUPPLIES (BLANKETS,EARPHONES ETC.)",
		"RESPONSIBLE": "CREWCA"
	},
	{
		"SUBCODE": "68S",
		"EXPLANATION": "LATE REPORTING OF TECHNICAL DEFECT BY CABIN CREW",
		"RESPONSIBLE": "CREWCA"
	},
	{
		"SUBCODE": "68X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CREWCA"
	},
	{
		"SUBCODE": "69A",
		"EXPLANATION": "CAPTAIN'S REQUEST FOR SECURITY CHECK (EXTRAORDINARY)",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "69X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "71A",
		"EXPLANATION": "OUTSIDE A/C LIMITS",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "71B",
		"EXPLANATION": "OUTSIDE CREW LIMITS (CAT 1 - CAT 2 ETC.)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "71R",
		"EXPLANATION": "OUTSIDE OPERATIONAL LIMITS",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "71X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "72A",
		"EXPLANATION": "OUTSIDE A/C LIMITS",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "72B",
		"EXPLANATION": "OUTSIDE CREW LIMITS (CAT 1 - CAT 2 ETC.)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "72R",
		"EXPLANATION": "OUTSIDE OPERATIONAL LIMITS",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "72X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "73A",
		"EXPLANATION": "OUTSIDE A/C LIMITS",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "73B",
		"EXPLANATION": "OUTSIDE CREW LIMITS (CAT 1 - CAT 2 ETC.)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "73R",
		"EXPLANATION": "OUTSIDE OPERATIONAL LIMITS",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "73X",
		"EXPLANATION": "ETOPS (AERODROMES AVAILABLE FOR LANDING WITH 2 AND 4 ENGINES) (due to ATFM regulatIon)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "73Y",
		"EXPLANATION": "OUTSIDE CREW LIMITS (CAT 1 - CAT 2 ETC.) (due to ATFM regulatIon)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "73Z",
		"EXPLANATION": "OUTSIDE A/C LIMITS (due to ATFM regulatIon)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "75A",
		"EXPLANATION": "DE-ICING/ANTI-ICING ON DESIGNATED REMOTE AREA",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "75B",
		"EXPLANATION": "DE-ICING/ANTI-ICING AT PARKING POSITION",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "75C",
		"EXPLANATION": "REPETITION OF DE-ICING AFTER HOLDOVER TIME EXCEEDED",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "75D",
		"EXPLANATION": "INADEQUATE EQUIPMENT/ INADEQUACY OF EXISTING EQUIPMENT DUE TO EXCESSIVE DEMAND",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "75E",
		"EXPLANATION": "INTERRUPTED DE-ICING SERVICE DUE TO EQUIPMENT BREAKDOWN DURING OPERATION",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "75F",
		"EXPLANATION": "INADEQUATE NUMBER OF STAFF",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "75G",
		"EXPLANATION": "LACK OF LIQUIDS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "75H",
		"EXPLANATION": "REMOVAL OF SNOW AND ICE FROM FAN BLADE OR PRE-STEP PROCESS.",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "75X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "76A",
		"EXPLANATION": "CLOSURE OF AIRPORT DUE TO SEVERE WEATHER CONDITIONS",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "76B",
		"EXPLANATION": "NON-AVAILABILITY OF PARKING POSITIONS DUE TO WEATHER CONDITIONS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "76C",
		"EXPLANATION": "REMOVAL OF SNOW, ICE, WATER AND SAND FROM AIRPORT",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "76X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "77A",
		"EXPLANATION": "INTERRUPTION OF FUEL SUPPLY OR SERVICES",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "77B",
		"EXPLANATION": "APRON CONDITIONS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "77C",
		"EXPLANATION": "HIGH WINDS /DOOR OPERATIONAL LIMITS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "77D",
		"EXPLANATION": "EXTENDED BOARDING TIME DUE TO WEATHER.",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "77X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "81Y",
		"EXPLANATION": "HIGH DEMAND OR CAPACITY",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "81Z",
		"EXPLANATION": "ATC ROUTING",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "82Q",
		"EXPLANATION": "EXTRAORDINARY DEMAND DUE TO CAPACITY REDUCTION IN NEIGHBORING AREA",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "82V",
		"EXPLANATION": "SPECIAL EVENTS (EVENT SHOULD BE EXPLAINED WITH SI)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "82W",
		"EXPLANATION": "MILITARY ACTIVITY ATFM",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "82X",
		"EXPLANATION": "STAFF SHORTAGE ATFM",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "82Y",
		"EXPLANATION": "EQUIPMENT FAILURE",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "82Z",
		"EXPLANATION": "INDUSTRIAL ACTIONS",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "83L",
		"EXPLANATION": "POLITICAL UNREST",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "83N",
		"EXPLANATION": "RADAR FAILURE",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "83O",
		"EXPLANATION": "CLOSED AIRPORT/RUNWAY",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "83R",
		"EXPLANATION": "OTHER",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "83S",
		"EXPLANATION": "NOISE ABATEMENT/NIGHT CURFEW",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "83T",
		"EXPLANATION": "SPECIAL EVENTS (EVENT SHOULD BE EXPLAINED WITH SI)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "83U",
		"EXPLANATION": "MILITARY ACTIVITY",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "83V",
		"EXPLANATION": "ACCIDENT/INCIDENT",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "83W",
		"EXPLANATION": "STAFF SHORTAGE",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "83X",
		"EXPLANATION": "EQUIPMENT FAILURES",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "83Y",
		"EXPLANATION": "INDUSTRIAL ACTIONS (STRIKE ETC.)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "83Z",
		"EXPLANATION": "HIGH DEMAND/ATC CAPACITY",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "84A",
		"EXPLANATION": "ATFM DUE TO WEATHER AT DESTINATION",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "85A",
		"EXPLANATION": "CONGESTION SECURITY CHECKPOINTS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "85B",
		"EXPLANATION": "BAGGAGE RECONCILIATION/FAILURE TO OFFLOADING THE BAGGAGE OF MISSING/ OFFLOADED PAX",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "85C",
		"EXPLANATION": "EXTRA/SPECIAL AIRPORT SECURITY FOR UNATTENDED ITEMS/PACKAGES INSIDE THE TERMINAL ",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "85D",
		"EXPLANATION": "BOMB WARNING",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "85E",
		"EXPLANATION": "SECURITY BREACH",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "85F",
		"EXPLANATION": "ADDITIONAL/SPECIAL SECURITY INSPECTIONS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "85G",
		"EXPLANATION": "MANDATORY PAX AND BAGGAGE OFFLOADING",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "85H",
		"EXPLANATION": "INADEQUATE NUMBER OF SECURITY STAFF",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "85I",
		"EXPLANATION": "EQUIPMENT FAILURE (COMPUTER, X-RAY EQUIPMENT FAILURES)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "85K",
		"EXPLANATION": "MANDATORY SECURITY CHECK OF TRANSIT PAX DUE TO LOCAL REGULATIONS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "85N",
		"EXPLANATION": "LATE OPENING OF THE SECURITY OFFICE AT THE FINAL CHECK POINT BEFORE BOARDING",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "85O",
		"EXPLANATION": "SECURITY DISCORDS  BETWEEN AUTHORITIES (AIRPORT SECURITY / POLICE DISPUTES)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "85P",
		"EXPLANATION": "SPECIAL SECURITY REQUIREMENTS INSIDE THE AIRPORT (PAX / BAG / CARRY-ON BAG)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "85S",
		"EXPLANATION": "SECURITY SEARCH DUE TO SUSPICIOUS PACKAGE (ON BOARD)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "85X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "86A",
		"EXPLANATION": "IMMIGRATION (PASSPORT)/CUSTOMS INFRASTRUCTURE SYSTEM",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "86B",
		"EXPLANATION": "INADEQUATE NUMBER OF STAFF",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "86C",
		"EXPLANATION": "HEALTH INCLUDING THE DELAYS DUE TO EPIDEMIC DISEASES DECLARED BY WHO.",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "86D",
		"EXPLANATION": "PAX TRAVELING WITH IMPROPER/INVALID/UNSATISFACTORY DOCS (INAD / DEPORTEE ETC.)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "86E",
		"EXPLANATION": "SPECIAL CHECK BY LOCAL AUTHORITIES FOR INBOUND PAX",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "86F",
		"EXPLANATION": "A/C DISINFECTION",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "86G",
		"EXPLANATION": "A/C CUSTOMS CLEARANCE PROCEDURES",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "86H",
		"EXPLANATION": "QUARANTINE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "86J",
		"EXPLANATION": "CONGESTION ON PASSPORT CHECK POINTS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "86N",
		"EXPLANATION": "CUSTOMS CONTROL ON INTERNAL/ TRANSFER BAGGAGE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "86O",
		"EXPLANATION": "PASSPORT COMPUTER SYSTEM FAILURE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "86P",
		"EXPLANATION": "IMMIGRATION PROCEDURES FOR CREW COMING FROM INTERNATIONAL FLIGHT AND CONTINUE TO DOMESTIC FLIGHT",
		"RESPONSIBLE": "CREWCA"
	},
	{
		"SUBCODE": "86T",
		"EXPLANATION": "LATE DEPORTEE / INAD PAX BOARDING",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "86X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "87A",
		"EXPLANATION": "LAST MINUTE GATE CHANGE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "87G",
		"EXPLANATION": "OCCURRING AT DEST: THIS CODE SHALL APPLY IF THE SLOT MSG INCLD GA87 OR EA87.",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "87H",
		"EXPLANATION": "LATE OR LACK OF FOLLOW-ME FOR PUSH BACK",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "87J",
		"EXPLANATION": "BREAK DOWN OF AIRPORT FUEL SYSTEMS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "87K",
		"EXPLANATION": "NO PUSH BACK CLEARANCE DUE TO CONSTRUCTION",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "87L",
		"EXPLANATION": "GROUND COMMUNICATION SYSTEM FAILURE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "87N",
		"EXPLANATION": "PUBLIC ADDRESS/FLIGHT INFORMATION DISPLAY SYSTEM FAILURE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "87P",
		"EXPLANATION": "PAX TRANSPORT SYSTEM FAILURE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "87R",
		"EXPLANATION": "ELECTRICAL SYSTEM FAILURE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "87S",
		"EXPLANATION": "LACK OF CHECK-IN COUNTERS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "87T",
		"EXPLANATION": "JET BRIDGE INOPERATIVE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "87U",
		"EXPLANATION": "NO PUSH BACK CLEARANCE DUE TO INFRASTRUCTURE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "87V",
		"EXPLANATION": "BAGGAGE SORTING SYSTEM DOWN/SLOW",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "87W",
		"EXPLANATION": "GATE LIMITATIONS/NO GATE AVAILABLE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "87Y",
		"EXPLANATION": "RAMP CONGESTION THIS CODE SHALL APPLY TO RELATED VEHICLES, EQUIPMENT AND STAFF.",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "87Z",
		"EXPLANATION": "LACK OF PARKING STANDS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "88A",
		"EXPLANATION": "RESTRICTIONS DUE TO CURFEW (OTHER THAN NIGHT CURFEW)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "88B",
		"EXPLANATION": "INDUSTRIAL ACTIONS (STRIKE ETC.)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "88C",
		"EXPLANATION": "POLITICAL UNREST",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "88D",
		"EXPLANATION": "AIRPORT CLOSURE",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "88E",
		"EXPLANATION": "RUNWAY CLOSURE",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "88G",
		"EXPLANATION": "PLANNED LATE DEPARTURE DUE TO ARRIVAL SLOT PENALTY",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "88N",
		"EXPLANATION": "NOISE RESTRICTIONS",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "88O",
		"EXPLANATION": "INADEQUATE NUMBER OF STAFF",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "88P",
		"EXPLANATION": "NIGHT CURFEW",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "88Q",
		"EXPLANATION": "SPECIAL FLIGHTS (VIP, MILITARY, CELEBRATION ETC.)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "89H",
		"EXPLANATION": "CONSTRUCTION WORK/MAINTENANCE",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "89J",
		"EXPLANATION": "LOST FLIGHT PLAN BY ATC",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "89K",
		"EXPLANATION": "START-UP/PUSH-BACK CLEARANCE DELAY (LOCAL ATC)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "89L",
		"EXPLANATION": "RUNWAY CLOSURE",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "89M",
		"EXPLANATION": "AIRPORT CLOSURE",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "89N",
		"EXPLANATION": "ATC ENVIRONMENTAL",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "89P",
		"EXPLANATION": "ATC POLITICAL UNREST",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "89R",
		"EXPLANATION": "ATC RESTRICTIONS DUE TO CURFEW SUCH AS NIGHT FLIGHT",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "89S",
		"EXPLANATION": "ATC WEATHER",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "89T",
		"EXPLANATION": "ATC SPECIAL EVENT",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "89U",
		"EXPLANATION": "ATC DUE TO DE-ICING",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "89V",
		"EXPLANATION": "ATC ACCIDENT/INCIDENT",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "89W",
		"EXPLANATION": "ATC EQUIPMENT",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "89X",
		"EXPLANATION": "ATC STAFFING",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "89Y",
		"EXPLANATION": "ATC INDUSTRIAL ACTION",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "89Z",
		"EXPLANATION": "ATC CAPACITY",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "89G",
		"EXPLANATION": "OTHER",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "91N",
		"EXPLANATION": "AWAITING PAX AND/OR BAGGAGE WITH CONNECTION FLIGHT",
		"RESPONSIBLE": "COMMERCIAL/SALES"
	},
	{
		"SUBCODE": "91O",
		"EXPLANATION": "AWAITING CONNECTION CARGO OR MAIL",
		"RESPONSIBLE": "COMMERCIAL/SALES"
	},
	{
		"SUBCODE": "91P",
		"EXPLANATION": "SHORT CONNECTION (PAX/BAGGAGE)",
		"RESPONSIBLE": "COMMERCIAL/SALES"
	},
	{
		"SUBCODE": "91R",
		"EXPLANATION": "AWAITING PAX AND BAG FROM A FLT, FOR WHICH OUR COMPANY ACTS AS MARKETING CARRIER",
		"RESPONSIBLE": "COMMERCIAL/SALES"
	},
	{
		"SUBCODE": "91X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "COMMERCIAL/SALES"
	},
	{
		"SUBCODE": "92A",
		"EXPLANATION": "FAILURE TO CONDUCT THROUGH CHECK-IN / INACCURATE TRANSIT/TRANSFER PAX & BAG",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "92B",
		"EXPLANATION": "MISSING/INCORRECT SEPARATION OF TRANSIT/TRANSFER/LOCAL LOADS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "92N",
		"EXPLANATION": "CHECK-IN ERROR / PAX AND BAGGAGE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "92O",
		"EXPLANATION": "CHECK-IN ERROR / PAX AND BAGGAGE (INCOMPLETE / INADEQUATE DOCUMENTATION)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "92X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "93D",
		"EXPLANATION": "LATE ARRIVAL DUE TO DIVERT OF INCOMING A/C / RE-ROUTING",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "93S",
		"EXPLANATION": "LATE ARRIVAL OF ANOTHER COMPANIES FLIGHT THAT IS PLANNED WITH SXS/SXD FLEET  (i.e. Late arrival of SXD /TK /Subcharter flight planned by SXS fleet, SXS /EW/Subcharter flight planned by SXD fleet etc.)",
		"RESPONSIBLE": "PUNCT"
	},
	{
		"SUBCODE": "93Y",
		"EXPLANATION": "LATE ARRIVAL DUE TO EN-ROUTE DELAY",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "93Z",
		"EXPLANATION": "LATE ARRIVAL DUE TO DEPARTURE DELAY AT THE PREVIOUS STATION",
		"RESPONSIBLE": "PUNCT"
	},
	{
		"SUBCODE": "94A",
		"EXPLANATION": "AWAITING OPERATING CABIN CREW OF THE FLIGHT",
		"RESPONSIBLE": "CRWP"
	},
	{
		"SUBCODE": "94B",
		"EXPLANATION": "AWAITING POSITIONING OR DEADHEAD CABIN CREW",
		"RESPONSIBLE": "CRWP"
	},
	{
		"SUBCODE": "94X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CRWP"
	},
	{
		"SUBCODE": "95A",
		"EXPLANATION": "AWAITING OPERATING ENTIRE CREW",
		"RESPONSIBLE": "CRWP"
	},
	{
		"SUBCODE": "95B",
		"EXPLANATION": "AWAITING POSITIONING OR DEADHEAD FLIGHT DECK OR ENTIRE CREW",
		"RESPONSIBLE": "CRWP"
	},
	{
		"SUBCODE": "95C",
		"EXPLANATION": "AWAITING OPERATING FLIGHT DECK CREW",
		"RESPONSIBLE": "CRWP"
	},
	{
		"SUBCODE": "95X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "CRWP"
	},
	{
		"SUBCODE": "96A",
		"EXPLANATION": "RE-ROUTING",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "96B",
		"EXPLANATION": "CONSOLIDATION OF FLIGHTS",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "96C",
		"EXPLANATION": "A/C / EQUIPMENT CHANGE / NON-TECHNICAL REASONS",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "96D",
		"EXPLANATION": "DIVERSION (DIVERSION REASON SHOULD BE DEFINED UNDER SI -TECHNIC/WEATHER /FUELING/CREW DUTY TIME OR SICKNESS/UNRULY-SICK PAX ETC.) ",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "96E",
		"EXPLANATION": "RESCHEDULED GROUND TIME LESS THAN DECLARED MINIMUM GROUND TIME",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "96F",
		"EXPLANATION": "LATE DISPATCH RELEASE",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "96G",
		"EXPLANATION": "CONTROLLER/ PLANNER ERROR",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "96H",
		"EXPLANATION": "OCC DISRUPTION",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "96N",
		"EXPLANATION": "NEW FUEL ARRANGEMENTS DUE TO OPERATIONAL REQUIREMENTS",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "96S",
		"EXPLANATION": "EMERGENCE OF SECONDARY CAUSES DUE TO TECHNICAL BREAKDOWN OR DAMAGE (THIS CODE WILL BE USED WHEN A/C CHANGES MADE AS THE RESULT OF AN A/C CHANGE DUE TO TECHNICAL PROBLEM OR DAMAGE AT A/C)",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "96T",
		"EXPLANATION": "RE-PLANNING DUE TO LACK OF A/C",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "96X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "OCC"
	},
	{
		"SUBCODE": "97A",
		"EXPLANATION": "WITHIN THE LOCAL STATION",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "97B",
		"EXPLANATION": "WITHIN THE ENTIRE COMPANY",
		"RESPONSIBLE": "PUNCT"
	},
	{
		"SUBCODE": "97D",
		"EXPLANATION": "WITHIN GROUND OPERATIONS",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "97E",
		"EXPLANATION": "WITHIN CARGO",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "97F",
		"EXPLANATION": "WITHIN CATERING",
		"RESPONSIBLE": "CATERING"
	},
	{
		"SUBCODE": "97G",
		"EXPLANATION": "WITHIN FLIGHT DECK CREW",
		"RESPONSIBLE": "CREWCO"
	},
	{
		"SUBCODE": "97H",
		"EXPLANATION": "WITHIN CABIN CREW",
		"RESPONSIBLE": "CREWCA"
	},
	{
		"SUBCODE": "97I",
		"EXPLANATION": "WITHIN TECHNICAL DEPARTMENT",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "97J",
		"EXPLANATION": "SUPPORT UNITS",
		"RESPONSIBLE": "PUNCT"
	},
	{
		"SUBCODE": "97X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "PUNCT"
	},
	{
		"SUBCODE": "98A",
		"EXPLANATION": "NATIONAL STRIKE",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "98B",
		"EXPLANATION": "WHOLE HANDLING COMPANY",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "98C",
		"EXPLANATION": "PAX SERVICES/HANDLING",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "98D",
		"EXPLANATION": "RAMP SERVICES/HANDLING",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "98E",
		"EXPLANATION": "CARGO",
		"RESPONSIBLE": "CARGO"
	},
	{
		"SUBCODE": "98F",
		"EXPLANATION": "CATERING",
		"RESPONSIBLE": "CATERING"
	},
	{
		"SUBCODE": "98G",
		"EXPLANATION": "TECHNIC",
		"RESPONSIBLE": "TECHNIC"
	},
	{
		"SUBCODE": "98H",
		"EXPLANATION": "CLEANING",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "98I",
		"EXPLANATION": "SUPPORT UNITS (PRM SERVICES, HEALTH SERVICES ETC.)",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "98J",
		"EXPLANATION": "FUEL",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "98L",
		"EXPLANATION": "SECURITY",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "98M",
		"EXPLANATION": "FIRE DEPARTMENT",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "98N",
		"EXPLANATION": "AUTHORITIES",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "98O",
		"EXPLANATION": "AIRPORT",
		"RESPONSIBLE": "GROUND"
	},
	{
		"SUBCODE": "98X",
		"EXPLANATION": "MISSING SLOT BECAUSE OF THIS REASON",
		"RESPONSIBLE": "PUNCT"
	},
	{
		"SUBCODE": "99A",
		"EXPLANATION": "MISCELLANEOUS (TO BE EXPLAINED IN SI)",
		"RESPONSIBLE": "PUNCT"
	},
	{
		"SUBCODE": "99B",
		"EXPLANATION": "WHEN THE FLIGHT HAS MORE THAN 4 DELAY REASONS, LAST 2 DELAY CODES WILL BE STATED UNDER 99B",
		"RESPONSIBLE": "PUNCT"
	},
	{
		"SUBCODE": "99C",
		"EXPLANATION": "LATE ARRIVAL OF PAX DUE TO SENT ISK MESSAGE",
		"RESPONSIBLE": "PUNCT"
	}
]